### PR TITLE
Make absolute dynamics also be the stop for the span dynamics.

### PR DESCRIPTION
**Pull request by rshura**
This should fix the export-example2.ly  -- @jpvoigt let me know if there's any more issues with that file,

### CODE REVIEW

**Comment by rshura** [comment]
This should fix the export-example2.ly  -- @jpvoigt let me know if there's any more issues with that file,

**Comment by jpvoigt** [comment]
Great! The Hairpin stops as expected. MuseScore still complains about bad placement of the wedge element (only in example2), but it loads correctly.

**Comment by rshura** [comment]
Can you tell me more?  What exactly is the problem with that XML?

**Comment by jpvoigt** [comment]
I can't tell you how it would be right, perhaps it is only a problem
with MuseScore, but still if you drop the file into
http://verovio.humdrum.org/ the hairpin is missing.

Where is the wedge to be placed according to the specs?



Am 08.11.18 um 07:44 schrieb Alex Roitman:
> Can you tell me more? What exactly is the problem with that XML?
>

**Comment by rshura** [comment]
The MusicXML docs show examples with wedge being under
direction->direction-type element:
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-wedge.htm

I think that's what I got. I don't know if the absolute dynamics should be
before or after the wedge. Maybe you can try changing that order and see if
it helps?

**Comment by jpvoigt** [comment]
Now I got it: wedge and dynamics both need there own direction-type element:

<direction>
<direction-type><wedge type="crescendo" /></direction-type>
<direction-type><dynamics><p /></dynamics></direction-type>
</direction>



Am 08.11.18 um 08:55 schrieb Alex Roitman:
> The MusicXML docs show examples with wedge being under
> direction->direction-type element:
> https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-wedge.htm
> 
> I think that's what I got. I don't know if the absolute dynamics should be
> before or after the wedge. Maybe you can try changing that order and see if
> it helps?
>

**Comment by rshura** [comment]
Great, did that and pushed directly to MusicXML-dev, it was a tiny change.

**Pull request merged**
